name: Build OPKG package

on:
  workflow_call:
    inputs:
      package-name:
        required: True
        type: string
      package-version:
        required: True
        type: string
      package-depends:
        type: string

jobs:
  build-opkg-package:
    name: Build OPKG package
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Download files
        uses: actions/download-artifact@v3
        with:
          name: opkg-package.tar.gz

      - name: Create control file
        run: |
          ls -la .
          tar xzfv opkg-package.tar.gz

          mkdir -pv opkg-package/control
          dpkg-deb \
            --showformat='Package: ${Package}\nDescription: ${binary:Summary}\n' \
            --show opkg-package/${{ inputs.package-name }}_${{ inputs.package-version }}*.deb \
            > opkg-package/control/control

          (
            echo "Maintainer: Michael Hacker <mh@superbox.one>"
            echo "Version: ${{ inputs.package-version }}"
            echo "Architecture: aarch64"
            echo "License: GPL-2.0"
          ) >> opkg-package/control/control

          if [ "${{ inputs.package-depends }}" != "" ]; then
            echo "Depends: ${{ inputs.package-depends }}" >> opkg-package/control/control
          fi

          echo "2.0" > opkg-package/debian-binary

      - name: Create conffiles file
        run: |
          find data/etc -type f | sed 's/data/\/usr\/local/g' > opkg-package/control/conffiles

      - name: Build OPKG package
        run: |
          sudo chown -R root:root opkg-package/*

          tar -C opkg-package/control -czvf opkg-package/control.tar.gz .
          tar -C opkg-package/data -czvf opkg-package/data.tar.gz .

          tar -C opkg-package -czvf \
            opkg-package/${{ inputs.package-name }}_${{ inputs.package-version }}_aarch64.ipk \
            control.tar.gz data.tar.gz debian-binary

      - name: Upload OPKG package
        uses: actions/upload-artifact@v3
        with:
          name: opkg-package
          path: opkg-package/*.ipk
