name: Unipi Modbus Tools

on:
  workflow_dispatch:

jobs:
  build-opkg:
    name: Build OPKG package
    runs-on: ubuntu-latest

    steps:
      - name: Download
        run: |
          wget https://repo.unipi.technology/debian/pool/main/u/unipi-tools/unipi-modbus-tools_1.3.4~buster_arm64.deb

      - name: Uncompress debian package
        run: |
          ar x unipi-modbus-tools_1.3.4~buster_arm64.deb
          
          mkdir -pv control
          tar xf control.tar.xz -C control
          
          mkdir -pv data
          tar xf data.tar.xz -C data

      - name: Create control file
        run: |
          mkdir -pv opkg-package/control
          dpkg-deb --showformat='Package: ${Package}\nVersion: ${Version}\nMaintainer: ${Maintainer}\nDescription: ${binary:Summary}\n' --show unipi-modbus-tools_1.3.4\~buster_arm64.deb > opkg-package/control/control 
          
          (
            echo "Architecture: aarch64"
            echo "License: GPL-2.0"
          ) >> opkg-package/control/control
          
          echo "2.0" > opkg-package/debian-binary

      - name: Collect data
        run: |
          mkdir -pv opkg-package/data/usr/local/opt/unipi/tools
          cp -v data/opt/unipi/tools/unipi_tcp_server opkg-package/data/usr/local/opt/unipi/tools/
          
          mkdir -pv opkg-package/data/usr/local/etc/default
          cp -v data/etc/default/unipitcp opkg-package/data/usr/local/etc/default/

      - name: Create conffiles file
        run: |
          find data/etc -type f | sed 's/data/\/usr\/local/g' > opkg-package/control/conffiles

      - name: Build OPKG package
        run: |
          tar -C opkg-package/control -czvf opkg-package/control.tar.gz .
          tar -C opkg-package/data -czvf opkg-package/data.tar.gz .

          sudo chown -R root:root opkg-package/*

          tar -C opkg-package -czvf \
            opkg-package/${{ inputs.package-name }}_${{ inputs.package-version }}_aarch64.ipk \
            control.tar.gz data.tar.gz debian-binary

      - name: Upload OPKG package
        uses: actions/upload-artifact@v3
        with:
          name: opkg-package
          path: opkg-package/*.ipk