name: Unipi Modbus Tools

on:
  workflow_dispatch:

jobs:
  prepare-data:
    name: Prepare data
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Download and uncompress debian package
        run: |
          wget ${{ inputs.repo-url }}/${{ inputs.package-name }}_${{ inputs.package-version }}~buster_arm64.deb
          ar x ${{ inputs.package-name }}_${{ inputs.package-version }}~buster_arm64.deb

      - name: Collect data
        run: |
          mkdir -pv opkg-package/data/usr/local/opt/unipi/tools
          cp -v data/opt/unipi/tools/unipi_tcp_server opkg-package/data/usr/local/opt/unipi/tools/
          
          mkdir -pv opkg-package/data/usr/local/etc/default
          cp -v data/etc/default/unipitcp opkg-package/data/usr/local/etc/default/
          
          cp -rv unipi-modbus-tools/data/* opkg-package/data/

      - name: Upload OPKG data
        uses: actions/upload-artifact@v3
        with:
          name: opkg-package
          path: opkg-package/*

  build-opkg-package:
    name: Build OPKG package
    needs:
      - prepare-data
    uses: ./.github/workflows/build-opkg-package.yml
    with:
      package-name: unipi-modbus-tools
      package-version: 1.3.4
      repo-url: https://repo.unipi.technology/debian/pool/main/u/unipi-tools

  publish-on-ftp:
    name: Publish on FTP
    needs:
      - build-opkg-package
    uses: superbox-dev/python-package-workflows/.github/workflows/publish-on-ftp.yml@main
    with:
      ftp-hostname: ${{ vars.FTP_HOSTNAME }}
      ftp-port: ${{ vars.FTP_PORT }}
      ftp-username: ${{ vars.FTP_USERNAME }}
      ftp-publish-path: ${{ vars.FTP_PUBLISH_PATH }}
    secrets:
      FTP_PASSWORD: ${{ secrets.FILES_SUPERBOX_ONE_FTP_PASSWORD }}
