name: Unipi Firmware Tools

on:
  workflow_dispatch:

env:
  PACKAGE_NAME: unipi-firmware-tools
  PACKAGE_VERSION: 2.8
  REPO_URL: https://repo.unipi.technology/debian/pool/main/u/unipi-tools

jobs:
  tests:
    name: Tests
    uses: ./.github/workflows/_tests.yml

  prepare-data:
    name: Prepare data
    runs-on: ubuntu-latest

    outputs:
      package-name: ${{ steps.parameters.outputs.package-name }}
      package-version: ${{ steps.parameters.outputs.package-version }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - id: parameters
        run: |
          echo "package-name=${{ env.PACKAGE_NAME }}" >> $GITHUB_OUTPUT
          echo "package-version=${{ env.PACKAGE_VERSION }}" >> $GITHUB_OUTPUT

      - name: Download and uncompress debian package
        # yamllint disable rule:line-length
        run: |
          wget ${{ env.REPO_URL }}/${{ steps.parameters.outputs.package-name }}_${{ steps.parameters.outputs.package-version }}~buster_arm64.deb
          ar x ${{ steps.parameters.outputs.package-name }}_${{ steps.parameters.outputs.package-version }}~buster_arm64.deb

          mkdir -pv control
          tar xf control.tar.xz -C control

          mkdir -pv data
          tar xf data.tar.xz -C data
        # yamllint enable rule:line-length

      - name: Collect data
        run: |
          mkdir -pv opkg-package/data/usr/local/opt/unipi/tools
          cp -v data/opt/unipi/tools/{fwserial,fwspi} opkg-package/data/usr/local/opt/unipi/tools/

          cp -v *.deb opkg-package/
          tar czvf opkg-package.tar.gz opkg-package

      - name: Upload OPKG data
        uses: actions/upload-artifact@v3
        with:
          name: opkg-package.tar.gz
          path: opkg-package.tar.gz

  build-opkg-package:
    name: Build OPKG package
    needs:
      - prepare-data
    uses: ./.github/workflows/build-opkg-package.yml
    with:
      package-name: ${{ needs.prepare-data.outputs.package-name }}
      package-version: ${{ needs.prepare-data.outputs.package-version }}

  publish-on-ftp:
    name: Publish on FTP
    needs:
      - build-opkg-package
    uses: superbox-dev/python-package-workflows/.github/workflows/publish-on-ftp.yml@main
    with:
      ftp-hostname: ${{ vars.FTP_HOSTNAME }}
      ftp-port: ${{ vars.FTP_PORT }}
      ftp-username: ${{ vars.FTP_USERNAME }}
      ftp-publish-path: ${{ vars.FTP_PUBLISH_PATH }}
    secrets:
      FTP_PASSWORD: ${{ secrets.FILES_SUPERBOX_ONE_FTP_PASSWORD }}
